config/routes.rb
Rails.application.routes.draw do
  root 'urls#index'
  resources :urls, except: :show
  get '/:slug', to: 'urls#show', as: :short
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/url.rb
class Url < ApplicationRecord
  validates :url, presence: true

  def self.generate_link(url)
    url = Url.new(url: url)
    return url unless url.valid?

    url.shortcode = SecureRandom.uuid[0..5]
    return url if url.save

    Url.generate_link(url)
  end

  def short
    Rails.application.routes.url_helpers.short_url(slug: self.shortcode)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def default_url_options
    if Rails.env.production?
      Rails.application.routes.default_url_options = { host: 'www.production-domain.com', protocol: 'https' }
    elsif Rails.env.development?
      Rails.application.routes.default_url_options = { host: 'localhost:3000', protocol: 'http' }
    end
  end
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  def index
    @urls = Url.all
  end

  def show
    @url = Url.find_by_shortcode(params[:slug])
    if @url.nil?
      render file: 'public/404.html', status: :not_found, layout: false
    else
      redirect_to @url.url
    end
  end

  def new
    @url = Url.new
  end

  def create
    @url = Url.generate_link(params[:url][:url])
    if @url.save
      flash[:notice] = 'You have successfully shortened URL.'
      redirect_to root_path
    else
      render 'new'
    end
  end

  def destroy
    @url = Url.find(params[:id])
    @url.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: "Url was successfully removed." }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortner</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

app/views/urls/_form.html.erb
<style>
.list-style {
  list-style: none;
}
</style>
<div class="text-center">
  <%= form_with(model: url, local: true) do |form| %>
    <% if url.errors.any? %>
      <div>
        <ul>
        <% url.errors.full_messages.each do |message| %>
          <li class="list-style"><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <h1>Enter URL</h1>
    <div class="field text-center">
      <%= form.text_field :url %>
    </div>

    <div class="actions text-center">
      <%= form.submit 'Save URL'%>
    </div>
  <% end %>
</div>

app/views/urls/edit.html.erb
<h1>Editing Url</h1>

<%= render 'form', url: @url %>

<%= link_to 'Show', @url %> |
<%= link_to 'Back', urls_path %>

app/views/urls/index.html.erb
<p id="notice"><%= notice %></p>

<table class="table">
  <thead>
    <tr>
      <th scope="col">URL</th>
      <th scope="col">Short Url</th>
      <th scope="col"><%= link_to 'Add URL',  new_url_path %></th>
    </tr>
  </thead>

  <tbody>
    <% @urls.each do |url| %>
      <tr>
        <td><%= url.url %></td>
        <td><%= link_to url.short , url.short  %></td>
        <td><%= link_to 'Remove', url, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/urls/new.html.erb
<%= render 'form', url: @url %>

<div class="text-center"><%= link_to 'Back', urls_path %></div>

app/views/urls/show.html.erb
<p id="notice"><%= notice %></p>

<p class="card text-center">
  <strong class="card-body">Url:</strong>
  <%= @url.url %>
  <strong class="card-body">Short URL:</strong>
  <%= link_to(@short_url, @url.url) %>
  <br><br>
  <%= link_to 'Back', urls_path %>
</p>